import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const routePath = resolve(root, "app/api/unsplash/route.ts");
const marker = "// Generated by scripts/next-dev.mjs. Do not commit this file.";

const routeSource = `${marker}
import { NextRequest, NextResponse } from "next/server";

const DEFAULT_PER_PAGE = 30;
const MAX_PER_PAGE = 30;

function parsePositiveInteger(value: string | null, fallback: number, maximum: number) {
  const parsed = Number.parseInt(value ?? "", 10);
  if (!Number.isFinite(parsed) || parsed < 1) return fallback;
  return Math.min(parsed, maximum);
}

function getUnsplashError(payload: unknown) {
  if (typeof payload === "object" && payload !== null && "errors" in payload) {
    const errors = payload.errors;
    if (Array.isArray(errors) && errors.length > 0) return errors.join("，");
  }
  return "Unsplash 请求失败";
}

export async function GET(request: NextRequest) {
  const apiKey = process.env.UNSPLASH_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ type: "error", errors: ["未配置 UNSPLASH_API_KEY"] }, { status: 500 });
  }

  const requestUrl = new URL(request.url);
  const query = requestUrl.searchParams.get("query")?.trim();
  const page = parsePositiveInteger(requestUrl.searchParams.get("page"), 1, 100);
  const perPage = parsePositiveInteger(requestUrl.searchParams.get("perPage"), DEFAULT_PER_PAGE, MAX_PER_PAGE);
  const upstreamUrl = new URL(query ? "https://api.unsplash.com/search/photos" : "https://api.unsplash.com/photos/random");

  if (query) {
    upstreamUrl.searchParams.set("query", query);
    upstreamUrl.searchParams.set("page", String(page));
    upstreamUrl.searchParams.set("per_page", String(perPage));
  } else {
    upstreamUrl.searchParams.set("count", String(perPage));
  }

  try {
    const upstreamResponse = await fetch(upstreamUrl, {
      headers: { accept: "application/json", authorization: \`Client-ID \${apiKey}\` },
    });
    const payload = await upstreamResponse.json();

    if (!upstreamResponse.ok) {
      return NextResponse.json(
        { type: "error", errors: [getUnsplashError(payload)] },
        { status: upstreamResponse.status >= 400 && upstreamResponse.status < 500 ? upstreamResponse.status : 502 },
      );
    }

    return NextResponse.json({ type: "success", response: payload });
  } catch {
    return NextResponse.json({ type: "error", errors: ["无法连接 Unsplash"] }, { status: 502 });
  }
}
`;

mkdirSync(dirname(routePath), { recursive: true });
writeFileSync(routePath, routeSource, "utf8");

let cleaned = false;
function cleanup() {
  if (cleaned) return;
  cleaned = true;
  if (existsSync(routePath) && readFileSync(routePath, "utf8").startsWith(marker)) {
    unlinkSync(routePath);
  }
}

const nextBin = resolve(root, "node_modules/next/dist/bin/next");
const nextArgs = process.argv.slice(2).filter((arg, index) => !(index === 0 && arg === "--"));
const child = spawn(process.execPath, [nextBin, "dev", ...nextArgs], {
  cwd: root,
  env: process.env,
  stdio: "inherit",
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    cleanup();
    child.kill(signal);
  });
}

child.on("close", (code, signal) => {
  cleanup();
  if (signal) process.kill(process.pid, signal);
  process.exit(code ?? 1);
});
